name: sudokode
description: An AI-powered Sudoku game built with Flutter and Dart. Challenge yourself with generated puzzles and get a little help when you're stuck.
publish_to: 'none'

version: 1.0.1+15

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_shared_components:
    git:
      url: https://github.com/SoloScripted/flutter-shared-components.git
  intl: ^0.19.0
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_launcher_icons: ^0.13.1
  rename: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/sudokode.png"
  adaptive_icon_background: "#000000"
  remove_alpha_ios: true
  